### ISSUE TITLE
super() call in SOLE/Person/SimplePerson.py fails

### ISSUE THREAD

**Issue by Stemist** [pachocanadian/sole#34]
To replicate, run

bash ./make.sh 

Which outputs:

_Reblacking python files: OK
Running unit tests: .....................................                                                                                   [100%]
37 passed in 0.06s
OK
Updating attribute documentation: Traceback (most recent call last):
  File "sole_attributes.py", line 13, in <module>
    person = Person()
  File "/home/quark/Development/sole/SOLE/Person/SimplePerson.py", line 7, in __init__
    super().__init__(attributes)
TypeError: super() takes at least 1 argument (0 given)
Exception AttributeError: "SimplePerson instance has no attribute 'settings'" in <bound method SimplePerson.__del__ of <SOLE.Person.SimplePerson.SimplePerson instance at 0x7fb4194c7290>> ignored
FAILED_

Relevent code:

class SimplePerson(BasePerson):
    def __init__(self, attributes=None):
        super().__init__(attributes)
        SOLE.log("[{}] SimplePerson->created".format(self.get("id")), SOLE.LOG_INFO)

    pass

**Comment by Stemist** [comment]
Fixed by adding new make_ubuntu.sh file that substitutes "python" for "python3" in bash script.
